services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    environment:
      - MONGODB_URI=${MONGODB_URI} # MongoDB Atlas connection string from .env
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - ALCHEMY_SIGNING_KEY=${ALCHEMY_SIGNING_KEY}
      - BEACON_CONTRACT=${BEACON_CONTRACT}
    volumes:
      - .:/app # Mounts current directory in the container for live development (Optional for production)
